"""empty message

Revision ID: 8ee784aaa232
Revises: 86d2266387c1
Create Date: 2024-06-05 16:38:46.151687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee784aaa232'
down_revision: Union[str, None] = '86d2266387c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_notifications_enabled', sa.Boolean(), nullable=False))
    op.drop_column('users', 'is_subscribed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_subscribed', sa.BOOLEAN(), nullable=False))
    op.drop_column('users', 'is_notifications_enabled')
    # ### end Alembic commands ###
